version: ">= 0.14.0"

formatter: markdown table

content: |-
  # IOS-XE PIM Configuration Example

  To run this example you need to execute:

  ```bash
  $ terraform init
  $ terraform plan
  $ terraform apply
  ```

  Note that this example will create resources. Resources can be destroyed with `terraform destroy`.

  #### `pim.nac.yaml`

  ```yaml
  {{ include "./pim.nac.yaml" }}
  ```

  #### `main.tf`

  ```hcl
  {{ include "./main.tf" }}
  ```

output:
  file: README.md
  mode: replace

sort:
  enabled: false

